// <auto-generated />
using LazyPinger.Base.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LazyPinger.Base.Migrations
{
    [DbContext(typeof(LazyPingerDbContext))]
    partial class LazyPingerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");
#pragma warning restore 612, 618
        }
    }
}
